### ISSUE TITLE
install error on ubunbu

### ISSUE THREAD

**Issue by ZhangAllen98** [jswhit/py-ncepbufr#10]
gfortran:f77: build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.f
/usr/bin/gfortran -Wall -g -L/home/zhangqw/mywrf/libraries/zlib/lib -L/home/zhangqw/mywrf/libraries/netcdf/lib -L/home/zhangqw/mywrf/libraries/HDF5/lib build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlibmodule.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/fortranobject.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.o -Lsrc -L/home/zhangqw/anaconda3/lib -lbufr -lpython3.5m -lgfortran -o build/lib.linux-x86_64-3.5/_bufrlib.cpython-35m-x86_64-linux-gnu.so
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
src/libbufr.a(bort2.o): In function `bort2_':
bort2.f:(.text+0x89): undefined reference to `bort_exit_'
src/libbufr.a(bort.o): In function `bort_':
bort.f:(.text+0x6c): undefined reference to `bort_exit_'
src/libbufr.a(cktaba.o): In function `cktaba_':
cktaba.f:(.text+0xf5): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
cktaba.f:(.text+0x908): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
src/libbufr.a(closbf.o): In function `closbf_':
closbf.f:(.text+0xde): undefined reference to `closfb_'
src/libbufr.a(cpdxmm.o): In function `cpdxmm_':
cpdxmm.f:(.text+0x9a): undefined reference to `backbufr_'
src/libbufr.a(msgwrt.o): In function `msgwrt_':
msgwrt.f:(.text+0x75a): undefined reference to `cwrbufr_'
src/libbufr.a(openbf.o): In function `openbf_':
openbf.f:(.text+0x3d7): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
openbf.f:(.text+0x738): undefined reference to `openab_'
openbf.f:(.text+0x791): undefined reference to `openrb_'
openbf.f:(.text+0x8e2): undefined reference to `openrb_'
openbf.f:(.text+0x914): undefined reference to `openwb_'
openbf.f:(.text+0x949): undefined reference to `openrb_'
openbf.f:(.text+0x970): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
openbf.f:(.text+0xa15): undefined reference to `openwb_'
openbf.f:(.text+0xa5a): undefined reference to `openwb_'
src/libbufr.a(posapx.o): In function `posapx_':
posapx.f:(.text+0x96): undefined reference to `backbufr_'
src/libbufr.a(rdbfdx.o): In function `rdbfdx_':
rdbfdx.f:(.text+0x72): undefined reference to `backbufr_'
src/libbufr.a(rdcmps.o): In function `rdcmps_':
rdcmps.f:(.text+0x41): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
src/libbufr.a(rdmsgw.o): In function `rdmsgw_':
rdmsgw.f:(.text+0x4a): undefined reference to `crdbufr_'
src/libbufr.a(readerme.o): In function `readerme_':
readerme.f:(.text+0x253): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
src/libbufr.a(readlc.o): In function `readlc_':
readlc.f:(.text+0x55c): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
readlc.f:(.text+0x569): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
readlc.f:(.text+0x8ac): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
readlc.f:(.text+0x94f): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
src/libbufr.a(readmg.o): In function `readmg_':
readmg.f:(.text+0x141): additional relocation overflows omitted from the output
readmg.f:(.text+0x157): undefined reference to `backbufr_'
src/libbufr.a(readmt.o): In function `readmt_':
readmt.f:(.text+0x15e4): undefined reference to `icvidx_'
src/libbufr.a(reads3.o): In function `reads3_':
reads3.f:(.text+0x578): undefined reference to `stseq_'
src/libbufr.a(rewnbf.o): In function `rewnbf_':
rewnbf.f:(.text+0x2bd): undefined reference to `cewind_'
src/libbufr.a(stndrd.o): In function `stndrd_':
stndrd.f:(.text+0x6ec): undefined reference to `restd_'
src/libbufr.a(ufbmem.o): In function `ufbmem_':
ufbmem.f:(.text+0x8a): undefined reference to `cewind_'
ufbmem.f:(.text+0x1b4): undefined reference to `backbufr_'
src/libbufr.a(ufbpos.o): In function `ufbpos_':
ufbpos.f:(.text+0x410): undefined reference to `cewind_'
collect2: error: ld returned 1 exit status
/usr/lib/gcc/x86_64-linux-gnu/4.8/../../../x86_64-linux-gnu/crt1.o: In function `_start':
(.text+0x20): undefined reference to `main'
src/libbufr.a(bort2.o): In function `bort2_':
bort2.f:(.text+0x89): undefined reference to `bort_exit_'
src/libbufr.a(bort.o): In function `bort_':
bort.f:(.text+0x6c): undefined reference to `bort_exit_'
src/libbufr.a(cktaba.o): In function `cktaba_':
cktaba.f:(.text+0xf5): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
cktaba.f:(.text+0x908): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
src/libbufr.a(closbf.o): In function `closbf_':
closbf.f:(.text+0xde): undefined reference to `closfb_'
src/libbufr.a(cpdxmm.o): In function `cpdxmm_':
cpdxmm.f:(.text+0x9a): undefined reference to `backbufr_'
src/libbufr.a(msgwrt.o): In function `msgwrt_':
msgwrt.f:(.text+0x75a): undefined reference to `cwrbufr_'
src/libbufr.a(openbf.o): In function `openbf_':
openbf.f:(.text+0x3d7): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
openbf.f:(.text+0x738): undefined reference to `openab_'
openbf.f:(.text+0x791): undefined reference to `openrb_'
openbf.f:(.text+0x8e2): undefined reference to `openrb_'
openbf.f:(.text+0x914): undefined reference to `openwb_'
openbf.f:(.text+0x949): undefined reference to `openrb_'
openbf.f:(.text+0x970): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
openbf.f:(.text+0xa15): undefined reference to `openwb_'
openbf.f:(.text+0xa5a): undefined reference to `openwb_'
src/libbufr.a(posapx.o): In function `posapx_':
posapx.f:(.text+0x96): undefined reference to `backbufr_'
src/libbufr.a(rdbfdx.o): In function `rdbfdx_':
rdbfdx.f:(.text+0x72): undefined reference to `backbufr_'
src/libbufr.a(rdcmps.o): In function `rdcmps_':
rdcmps.f:(.text+0x41): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
src/libbufr.a(rdmsgw.o): In function `rdmsgw_':
rdmsgw.f:(.text+0x4a): undefined reference to `crdbufr_'
src/libbufr.a(readerme.o): In function `readerme_':
readerme.f:(.text+0x253): relocation truncated to fit: R_X86_64_PC32 against symbol `sc3bfr_' defined in COMMON section in src/libbufr.a(reads3.o)
src/libbufr.a(readlc.o): In function `readlc_':
readlc.f:(.text+0x55c): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
readlc.f:(.text+0x569): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
readlc.f:(.text+0x8ac): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
readlc.f:(.text+0x94f): relocation truncated to fit: R_X86_64_PC32 against symbol `rlccmn_' defined in COMMON section in src/libbufr.a(rdcmps.o)
src/libbufr.a(readmg.o): In function `readmg_':
readmg.f:(.text+0x141): additional relocation overflows omitted from the output
readmg.f:(.text+0x157): undefined reference to `backbufr_'
src/libbufr.a(readmt.o): In function `readmt_':
readmt.f:(.text+0x15e4): undefined reference to `icvidx_'
src/libbufr.a(reads3.o): In function `reads3_':
reads3.f:(.text+0x578): undefined reference to `stseq_'
src/libbufr.a(rewnbf.o): In function `rewnbf_':
rewnbf.f:(.text+0x2bd): undefined reference to `cewind_'
src/libbufr.a(stndrd.o): In function `stndrd_':
stndrd.f:(.text+0x6ec): undefined reference to `restd_'
src/libbufr.a(ufbmem.o): In function `ufbmem_':
ufbmem.f:(.text+0x8a): undefined reference to `cewind_'
ufbmem.f:(.text+0x1b4): undefined reference to `backbufr_'
src/libbufr.a(ufbpos.o): In function `ufbpos_':
ufbpos.f:(.text+0x410): undefined reference to `cewind_'
collect2: error: ld returned 1 exit status
analyzevars: charselector={'len': '8'} unhandled.analyzevars: charselector={'len': '8'} unhandled.error: Command "/usr/bin/gfortran -Wall -g -L/home/zhangqw/mywrf/libraries/zlib/lib -L/home/zhangqw/mywrf/libraries/netcdf/lib -L/home/zhangqw/mywrf/libraries/HDF5/lib build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlibmodule.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/fortranobject.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.o -Lsrc -L/home/zhangqw/anaconda3/lib -lbufr -lpython3.5m -lgfortran -o build/lib.linux-x86_64-3.5/_bufrlib.cpython-35m-x86_64-linux-gnu.so" failed with exit status 1

**Comment by ZhangAllen98** [comment]
**Another Case**
customize Gnu95FCompiler using build_ext
building '_bufrlib' extension
compiling C sources
C compiler: gcc -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -O3 -fPIC -fPIC

compile options: '-Ibuild/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src -I/home/zhangqw/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/zhangqw/anaconda3/include/python3.5m -c'
compiling Fortran sources
Fortran f77 compiler: gfortran -Wall -g -ffixed-form -fno-second-underscore -m64 -O3 -funroll-loops
Fortran f90 compiler: /usr/bin/gfortran -Wall -g -fno-second-underscore -m64 -O3 -funroll-loops
Fortran fix compiler: /usr/bin/gfortran -Wall -g -ffixed-form -fno-second-underscore -Wall -g -fno-second-underscore -m64 -O3 -funroll-loops
compile options: '-Ibuild/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src -I/home/zhangqw/anaconda3/lib/python3.5/site-packages/numpy/core/include -I/home/zhangqw/anaconda3/include/python3.5m -c'
gfortran:f77: build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.f
/usr/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlibmodule.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/fortranobject.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.o -Lsrc -L/home/zhangqw/anaconda3/lib -lbufr -lpython3.5m -lgfortran -o build/lib.linux-x86_64-3.5/_bufrlib.cpython-35m-x86_64-linux-gnu.so
/usr/bin/ld: build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.o: **relocation R_X86_64_32 against `hrdwrd_' can not be used when making a shared object; recompile with -fPIC**
build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.o: error adding symbols: Bad value
collect2: error: ld returned 1 exit status
/usr/bin/ld: build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.o: **relocation R_X86_64_32 against `hrdwrd_' can not be used when making a shared object; recompile with -fPIC**
build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.o: error adding **symbols: Bad value
collect2: error: ld returned 1 exit status**
error: Command "/usr/bin/gfortran -Wall -g -Wall -g -shared build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlibmodule.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/fortranobject.o build/temp.linux-x86_64-3.5/build/src.linux-x86_64-3.5/src/_bufrlib-f2pywrappers.o -Lsrc -L/home/zhangqw/anaconda3/lib -lbufr -lpython3.5m -lgfortran -o build/lib.linux-x86_64-3.5/_bufrlib.cpython-35m-x86_64-linux-gnu.so" failed with exit status 1

**Comment by jswhit** [comment]
user reports problem solved by upgrading numpy from 1.13.1 to 1.13.3
